import { useEffect, useState } from 'react'
import { App, Button, Card, Col, Form, Input, Modal, Popconfirm, Row, Select, Space, Statistic, Switch, Table, Tag, Typography, type TableProps } from 'antd'
import { PlusOutlined, SearchOutlined } from '@ant-design/icons'
import { useNavigate } from 'react-router-dom'
import { DataState, PageShell } from '../../components/PageShell'
import { StatusTag } from '../../components/StatusTag'
import { useIdentity } from '../../features/identity/IdentityProvider'
import type { AdminEmployee, AdminOverview, AdminReferences } from '../../types/api'

const actionToken = () => `ADMIN-${crypto.randomUUID()}`

export function AdminDashboardPage() {
  const { backend } = useIdentity(); const navigate = useNavigate()
  const [data,setData]=useState<AdminOverview|null>(null);const[error,setError]=useState<string|null>(null)
  const load=async()=>{setError(null);try{setData(await backend.adminOverview())}catch(err){setError(err instanceof Error?err.message:'管理工作台加载失败')}}
  useEffect(()=>{void load()},[backend])
  return <PageShell title="系统管理工作台" description="查看平台基础运营信息并管理员工资料">
    <DataState loading={!data&&!error} error={error} empty={false} onRetry={load}>{data&&<>
      <Row gutter={[16,16]}><Col xs={24} md={8}><Card><Statistic title="员工数量" value={data.employee_count}/></Card></Col><Col xs={24} md={8}><Card><Statistic title="供应商数量" value={data.supplier_count}/></Card></Col><Col xs={24} md={8}><Card><Statistic title="采购申请总量" value={data.requirement_count}/></Card></Col></Row>
      <Card className="welcome-card" variant="borderless"><div><Typography.Title level={3}>常用管理入口</Typography.Title><Typography.Paragraph>管理员不参与审批、采购或入库，仅维护平台资料并查看全局数据。</Typography.Paragraph><Space wrap><Button type="primary" onClick={()=>navigate('/admin/employees')}>员工管理</Button><Button onClick={()=>navigate('/admin/requirements')}>采购清单</Button><Button onClick={()=>navigate('/admin/suppliers')}>供应商查询</Button></Space></div></Card>
      <Row gutter={[18,18]}><Col xs={24} xl={12}><Card title="最近员工变更"><Table size="small" rowKey="employee_id" dataSource={data.recent_employees} pagination={false} columns={[{title:'员工',dataIndex:'name'},{title:'角色',render:(_,item)=>item.roles.map((role)=>role.role_name).join(' / ')||'—'},{title:'状态',render:(_,item)=><Tag color={item.status?'success':'default'}>{item.status?'正常':'已停用'}</Tag>}]}/></Card></Col><Col xs={24} xl={12}><Card title="最近采购记录"><Table size="small" rowKey="requirement_id" dataSource={data.recent_requirements} pagination={false} columns={[{title:'采购单号',dataIndex:'requirement_no'},{title:'设备',dataIndex:'device_name'},{title:'状态',dataIndex:'status',render:(value)=><StatusTag status={value}/>},{title:'操作',render:(_,item)=><Button type="link" onClick={()=>navigate(`/requirements/${item.requirement_id}`)}>查看</Button>}]}/></Card></Col></Row>
    </>}</DataState>
  </PageShell>
}

export function AdminEmployeesPage() {
  const {backend}=useIdentity();const{message}=App.useApp();const[form]=Form.useForm();const[data,setData]=useState<{items:AdminEmployee[];total:number}>({items:[],total:0});const[refs,setRefs]=useState<AdminReferences>({roles:[],buildings:[]});const[keyword,setKeyword]=useState('');const[activeKeyword,setActiveKeyword]=useState('');const[page,setPage]=useState(1);const[loading,setLoading]=useState(true);const[error,setError]=useState<string|null>(null);const[editing,setEditing]=useState<AdminEmployee|null|undefined>(undefined);const[saving,setSaving]=useState(false)
  const load=async()=>{setLoading(true);setError(null);try{const[list,references]=await Promise.all([backend.adminEmployees({keyword:activeKeyword||undefined,page,page_size:20}),backend.adminReferences()]);setData(list);setRefs(references)}catch(err){setError(err instanceof Error?err.message:'员工列表加载失败')}finally{setLoading(false)}}
  useEffect(()=>{void load()},[backend,page,activeKeyword])
  const open=(item:AdminEmployee|null)=>{setEditing(item);form.resetFields();form.setFieldsValue(item?{employee_no:item.employee_no,name:item.name,mobile:item.mobile,status:item.status,role_codes:item.roles.map((value)=>value.role_code),building_ids:item.buildings.map((value)=>value.building_id),primary_building_id:item.buildings.find((value)=>value.is_primary)?.building_id,platform_type:item.identities[0]?.platform_type||'TEST_PLATFORM',platform_user_id:item.identities[0]?.platform_user_id}:{status:true,platform_type:'TEST_PLATFORM',role_codes:[],building_ids:[]})}
  const save=async()=>{try{const values=await form.validateFields();setSaving(true);const body={...values,action_token:actionToken()};if(editing)await backend.updateAdminEmployee(editing.employee_id,body);else await backend.createAdminEmployee(body);message.success(editing?'员工资料已更新':'员工已新增');setEditing(undefined);await load()}catch(err){if(err&&typeof err==='object'&&'errorFields'in err)return;message.error(err instanceof Error?err.message:'保存失败')}finally{setSaving(false)}}
  const deactivate=async(item:AdminEmployee)=>{try{await backend.deactivateAdminEmployee(item.employee_id,actionToken());message.success('员工账号已停用');await load()}catch(err){message.error(err instanceof Error?err.message:'停用失败')}}
  const columns:TableProps<AdminEmployee>['columns']=[{title:'员工编号',dataIndex:'employee_no',render:(value)=>value||'—'},{title:'姓名',dataIndex:'name',render:(value)=><Typography.Text strong>{value}</Typography.Text>},{title:'手机号',dataIndex:'mobile',render:(value)=>value||'—'},{title:'角色',render:(_,item)=>item.roles.map((value)=>value.role_name).join(' / ')||'—'},{title:'所属楼宇',render:(_,item)=>item.buildings.map((value)=>value.building_name).join(' / ')||'—'},{title:'账号状态',render:(_,item)=><Tag color={item.status?'success':'default'}>{item.status?'正常':'已停用'}</Tag>},{title:'操作',render:(_,item)=><Space><Button type="link" onClick={()=>open(item)}>查看 / 编辑</Button>{item.status&&<Popconfirm title="确认停用该员工账号？" description="停用后该员工及平台身份将无法继续访问系统。" onConfirm={()=>deactivate(item)}><Button type="link" danger>停用</Button></Popconfirm>}</Space>}]
  return <PageShell title="员工管理" description="管理员工资料、所属楼宇、角色和平台身份" extra={<Button type="primary" icon={<PlusOutlined/>} onClick={()=>open(null)}>新增员工</Button>}><Card className="filter-card"><Space.Compact style={{width:420,maxWidth:'100%'}}><Input value={keyword} onChange={(event)=>setKeyword(event.target.value)} onPressEnter={()=>{setPage(1);setActiveKeyword(keyword.trim())}} placeholder="搜索姓名、编号或手机号"/><Button type="primary" icon={<SearchOutlined/>} onClick={()=>{setPage(1);setActiveKeyword(keyword.trim())}}>搜索</Button></Space.Compact></Card><DataState loading={loading} error={error} empty={!data.items.length} onRetry={load}><Card className="table-card"><Table rowKey="employee_id" columns={columns} dataSource={data.items} pagination={{current:page,pageSize:20,total:data.total,onChange:setPage,showTotal:(total)=>`共 ${total} 名员工`}} scroll={{x:1000}}/></Card></DataState><Modal open={editing!==undefined} title={editing?'查看 / 编辑员工':'新增员工'} width={680} onCancel={()=>setEditing(undefined)} onOk={save} confirmLoading={saving} destroyOnHidden><Form form={form} layout="vertical"><Row gutter={16}><Col span={12}><Form.Item name="employee_no" label="员工编号"><Input/></Form.Item></Col><Col span={12}><Form.Item name="name" label="姓名" rules={[{required:true,message:'请填写姓名'}]}><Input/></Form.Item></Col></Row><Form.Item name="mobile" label="手机号"><Input/></Form.Item><Form.Item name="role_codes" label="角色" rules={[{required:true,message:'请选择角色'}]}><Select mode="multiple" options={refs.roles.map((item)=>({value:item.role_code,label:item.role_name}))}/></Form.Item><Form.Item name="building_ids" label="所属楼宇"><Select mode="multiple" options={refs.buildings.map((item)=>({value:item.building_id,label:item.building_name}))}/></Form.Item><Form.Item name="primary_building_id" label="主楼宇"><Select allowClear options={refs.buildings.map((item)=>({value:item.building_id,label:item.building_name}))}/></Form.Item><Row gutter={16}><Col span={10}><Form.Item name="platform_type" label="身份平台" rules={[{required:true}]}><Select options={[{value:'TEST_PLATFORM',label:'本地测试平台'}]}/></Form.Item></Col><Col span={14}><Form.Item name="platform_user_id" label="平台账号标识" rules={[{required:true,message:'请填写平台账号标识'}]}><Input placeholder="例如 test-user-09"/></Form.Item></Col></Row><Form.Item name="status" label="账号状态" valuePropName="checked"><Switch checkedChildren="启用" unCheckedChildren="停用"/></Form.Item><AlertCredentialNotice/></Form></Modal></PageShell>
}

function AlertCredentialNotice(){return <Card size="small" style={{background:'#f6faff'}}><Typography.Text type="secondary">当前系统使用平台身份和服务端签名认证，不保存本地登录密码。管理员可维护平台账号标识，但不能查看或设置不存在的明文密码。</Typography.Text></Card>}
